# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:

  # Main Site
  multisite.com:
    site_hosts:
      - canonical: site.dev
    local_path: ../site # local Bedrock site path directory (relative to Ansible root)
    admin_email: admin@site.dev
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false

  # Site 2
  # site2.com:
  #   site_hosts:
  #     - canonical: site2.dev
  #       redirects:
  #         - www.site2.dev
  #   local_path: ../site2 # local Bedrock site path directory (relative to Ansible root)
  #   admin_email: admin@site2.dev
  #   multisite:
  #     enabled: true
  #     subdomains: false
  #   ssl:
  #     enabled: false
  #     provider: self-signed
  #   cache:
  #     enabled: false